# Generated by Django 2.2.6 on 2019-10-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='union_name',
            field=models.CharField(max_length=100),
        ),
    ]
