# Generated by Django 2.2.6 on 2019-10-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Package'),
        ),
    ]
