# Generated by Django 2.2.6 on 2019-10-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Package'),
        ),
    ]
