# Generated by Django 2.2.6 on 2019-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Customer ID'),
        ),
    ]
