# Generated by Django 2.2.6 on 2019-10-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20191006_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alter_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
