# Generated by Django 2.2.6 on 2019-10-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20191009_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='0F700D', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
