# Generated by Django 2.2.6 on 2019-10-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20191009_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='0098FF', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
