# Generated by Django 2.2.6 on 2019-10-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Package'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CDBFDP', max_length=100, verbose_name='Customer ID'),
        ),
    ]
