# Generated by Django 2.2.6 on 2019-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20191006_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='package',
            new_name='package_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='X12KNQ', max_length=100, verbose_name='Customer ID'),
        ),
    ]
