# Generated by Django 2.2.6 on 2019-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20191009_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='828078', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
