# Generated by Django 2.2.6 on 2019-10-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20191006_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='5S621C', max_length=100, verbose_name='Customer ID'),
        ),
    ]
