# Generated by Django 2.2.6 on 2019-10-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20191009_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='61F7D0', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
