# Generated by Django 2.2.6 on 2019-10-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20191006_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='4H16AH', max_length=100, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_bill',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(default='', max_length=100, verbose_name='Package'),
        ),
    ]
