# Generated by Django 2.2.6 on 2019-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20191006_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='EB5395', max_length=100, verbose_name='Customer ID'),
        ),
    ]
