# Generated by Django 2.2.6 on 2019-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20191006_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='customer',
            name='total_due',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='RP1GMB', max_length=100, verbose_name='Customer ID'),
        ),
    ]
