# Generated by Django 2.2.6 on 2019-10-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20191006_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='8PX7RX', max_length=100, verbose_name='Customer ID'),
        ),
    ]
