# Generated by Django 2.2.6 on 2019-10-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20191006_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='5AT93M', max_length=100, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
