# Generated by Django 2.2.6 on 2019-10-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20191006_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='PA1ZPS', max_length=100, verbose_name='Customer ID'),
        ),
    ]
