# Generated by Django 2.2.6 on 2019-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20191009_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='2AA4D3', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
