# Generated by Django 2.2.6 on 2019-10-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20191006_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='18AQ19', max_length=100, verbose_name='Customer ID'),
        ),
    ]
