# Generated by Django 2.2.6 on 2019-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_auto_20191010_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='104488', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
