# Generated by Django 2.2.6 on 2019-10-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_auto_20191006_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='ZQNHC5', max_length=100, verbose_name='Customer ID'),
        ),
    ]
