# Generated by Django 2.2.6 on 2019-10-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20191006_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='H3RG88', max_length=100, verbose_name='Customer ID'),
        ),
    ]
