# Generated by Django 2.2.6 on 2019-10-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_auto_20191006_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='EEPM6X', max_length=100, verbose_name='Customer ID'),
        ),
    ]
