# Generated by Django 2.2.6 on 2019-10-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_auto_20191011_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='06D83A', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
