# Generated by Django 2.2.6 on 2019-10-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_auto_20191006_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='C1NG69', max_length=100, verbose_name='Customer ID'),
        ),
    ]
