# Generated by Django 2.2.6 on 2019-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_auto_20191017_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='232098', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
