# Generated by Django 2.2.6 on 2019-10-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_auto_20191019_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='55D24D', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
