# Generated by Django 2.2.6 on 2019-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_auto_20191006_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='77G6X2', max_length=100, verbose_name='Customer ID'),
        ),
    ]
