# Generated by Django 2.2.6 on 2019-10-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_auto_20191006_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='month_cycle',
            field=models.IntegerField(default=30, verbose_name='Month Cycle'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='QMND5G', max_length=100, verbose_name='Customer ID'),
        ),
    ]
