# Generated by Django 2.2.6 on 2019-10-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_auto_20191006_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='per_day_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='A9CR5C', max_length=100, verbose_name='Customer ID'),
        ),
    ]
