# Generated by Django 2.2.6 on 2019-10-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_auto_20191021_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='458F51', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
