# Generated by Django 2.2.6 on 2019-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_auto_20191006_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='3CFX76', max_length=100, verbose_name='Customer ID'),
        ),
    ]
