# Generated by Django 2.2.6 on 2019-10-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0059_auto_20191006_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='ZT6PS7', max_length=100, verbose_name='Customer ID'),
        ),
    ]
