# Generated by Django 2.2.6 on 2019-10-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0061_auto_20191022_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='46FFDA', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
