# Generated by Django 2.2.6 on 2019-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_auto_20191006_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='MKSCXQ', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
