# Generated by Django 2.2.6 on 2019-10-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_auto_20191007_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='757472', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
