# Generated by Django 2.2.6 on 2019-10-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_auto_20191022_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='D503A7', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
