# Generated by Django 2.2.6 on 2019-10-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0067_auto_20191023_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='8F7820', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
