# Generated by Django 2.2.6 on 2019-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0068_auto_20191007_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='6DA370', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
