# Generated by Django 2.2.6 on 2019-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0068_auto_20191023_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='592F42', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
