# Generated by Django 2.2.6 on 2019-10-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0071_auto_20191025_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='820369', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
