# Generated by Django 2.2.6 on 2019-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0071_auto_20191007_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='A49928', max_length=100, unique=True, verbose_name='Customer ID'),
        ),
    ]
