# Generated by Django 2.2.6 on 2019-10-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0075_auto_20191025_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='51A92A', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
