# Generated by Django 2.2.6 on 2019-10-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0076_auto_20191025_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='564334', max_length=6, unique=True, verbose_name='Customer ID'),
        ),
    ]
