# Generated by Django 2.2.6 on 2019-10-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(default='W6462L', max_length=6, unique=True, verbose_name='Bill ID')),
                ('billing_start_date', models.DateField()),
                ('balance', models.FloatField(default=0)),
                ('total_bill', models.FloatField(default=0, verbose_name='Total Bill')),
                ('due_bill_status', models.BooleanField(default=True, verbose_name='Due Status')),
                ('due_bill', models.FloatField(default=0, verbose_name='Due Bill')),
                ('total_day', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Invoice ID')),
                ('invoice_type', models.CharField(choices=[('0', 'Due Bill'), ('1', 'New Connection'), ('2', 'Current Bill')], default='2', max_length=1)),
                ('invoice_amount', models.FloatField(default=0, verbose_name='Invoice Amount')),
                ('adjustment', models.FloatField(blank=True, default=0, null=True)),
                ('custom_bill_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Bill')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
