# Generated by Django 2.2.6 on 2019-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20191006_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='6DF53K2P', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
