# Generated by Django 2.2.6 on 2019-10-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20191006_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='433L3F22', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
