# Generated by Django 2.2.6 on 2019-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20191009_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='K65YK6', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
