# Generated by Django 2.2.6 on 2019-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20191006_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='K343435P', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
