# Generated by Django 2.2.6 on 2019-10-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20191006_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_bill',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_due_bill',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='DK5D533F', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
