# Generated by Django 2.2.6 on 2019-10-08 20:51

from django.db import migrations, models
import  datetime


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20191009_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='YK4WYC', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='custom_bill_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 1)),
            preserve_default=False,
        ),
    ]
