# Generated by Django 2.2.6 on 2019-10-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_auto_20191006_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='current_bill',
            field=models.FloatField(default=0, verbose_name='Current Bill'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='46D536FL', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
