# Generated by Django 2.2.6 on 2019-10-05 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill', '0010_auto_20191006_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='F332LPL4', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
