# Generated by Django 2.2.6 on 2019-10-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_auto_20191006_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='bill_customer',
            new_name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='L3DKKD5K', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
