# Generated by Django 2.2.6 on 2019-10-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_auto_20191006_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='24DLP6L4', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
