# Generated by Django 2.2.6 on 2019-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_auto_20191006_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='2K3P266D', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
