# Generated by Django 2.2.6 on 2019-10-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_auto_20191006_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='6432P2', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='F6FK55PD', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
