# Generated by Django 2.2.6 on 2019-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0016_auto_20191009_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='L4Y466', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
