# Generated by Django 2.2.6 on 2019-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0021_auto_20191009_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='P65522', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
