# Generated by Django 2.2.6 on 2019-10-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0023_auto_20191006_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('0', 'Due Bill'), ('1', 'New Connection'), ('2', 'Current Bill')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='PP5C26', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='L65FKL65', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
