# Generated by Django 2.2.6 on 2019-10-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0024_auto_20191006_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='balance',
            new_name='total_balance',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='current_bill',
            new_name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='due_bill',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='#APPKP', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='LF5KDKDF', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
