# Generated by Django 2.2.6 on 2019-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0024_auto_20191009_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='C23K63', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
