# Generated by Django 2.2.6 on 2019-10-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0025_auto_20191006_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='bill',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='due_bill_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='LPL5A3', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_bill',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_due_bill',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='KFP3P4P2', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
