# Generated by Django 2.2.6 on 2019-10-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0027_auto_20191006_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='Y3L5A6', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='LDF6PPD4', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
