# Generated by Django 2.2.6 on 2019-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0027_auto_20191010_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='due_bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='connection_bill',
            field=models.FloatField(blank=0, default=0, null=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='user_bill_paid',
            field=models.FloatField(blank=0, default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='user_has_bill',
            field=models.FloatField(blank=0, default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='K6K5PL', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='invoice_bill_collector',
            field=models.FloatField(blank=0, default=0),
        ),
    ]
