# Generated by Django 2.2.6 on 2019-10-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0028_auto_20191010_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='invoice_bill_collector',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='LK2LAY', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
