# Generated by Django 2.2.6 on 2019-10-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0028_auto_20191006_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_bill',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='CP#3L5', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.FloatField(default=0, verbose_name='Invoice Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='3LDDF43P', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
