# Generated by Django 2.2.6 on 2019-10-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0029_auto_20191006_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_bill',
            field=models.FloatField(default=0, verbose_name='Total Bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='5ALA42', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='LLLL5456', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
