# Generated by Django 2.2.6 on 2019-10-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0031_auto_20191006_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='3A4L#P', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='5LDP4LFF', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
