# Generated by Django 2.2.6 on 2019-10-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0032_auto_20191011_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='666P5L', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='billhistory',
            name='text',
            field=models.DateField(),
        ),
    ]
