# Generated by Django 2.2.6 on 2019-10-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0033_auto_20191011_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billhistory',
            old_name='text',
            new_name='text_date',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='L5CW5A', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
