# Generated by Django 2.2.6 on 2019-10-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0035_auto_20191011_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='billhistory',
            name='total_days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='billhistory',
            name='user_new_bill',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='22K4CP', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
