# Generated by Django 2.2.6 on 2019-10-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0036_auto_20191011_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='KAY45W', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='billhistory',
            name='total_days',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
