# Generated by Django 2.2.6 on 2019-10-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0038_auto_20191011_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='3KWKP3', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='billhistory',
            name='total_days',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
