# Generated by Django 2.2.6 on 2019-10-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0039_auto_20191011_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_day_for_new_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='CLLKP4', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
