# Generated by Django 2.2.6 on 2019-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0040_auto_20191006_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='6PK2PP', max_length=6, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='K5DPL556', max_length=8, verbose_name='Invoice ID'),
        ),
    ]
