# Generated by Django 2.2.6 on 2019-10-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0040_auto_20191011_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='total_day_for_new_date',
            new_name='last_total_day_for_new_date',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='LL544K', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
