# Generated by Django 2.2.6 on 2019-10-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0042_auto_20191011_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='25PW24', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
