# Generated by Django 2.2.6 on 2019-10-10 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0043_auto_20191011_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='billhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='YAP4K2', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
