# Generated by Django 2.2.6 on 2019-10-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0046_auto_20191011_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='CKWK55', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
