# Generated by Django 2.2.6 on 2019-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0048_auto_20191017_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='PLW5KL', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
