# Generated by Django 2.2.6 on 2019-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0048_auto_20191007_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='PP52PL', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='5LP5F335', max_length=8, unique=True, verbose_name='Invoice ID'),
        ),
    ]
