# Generated by Django 2.2.6 on 2019-10-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0050_auto_20191017_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='WYA425', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
