# Generated by Django 2.2.6 on 2019-10-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0050_auto_20191007_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='KKPC66', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='434462K2', max_length=8, unique=True, verbose_name='Invoice ID'),
        ),
    ]
