# Generated by Django 2.2.6 on 2019-10-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0051_auto_20191019_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-custom_bill_date',)},
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='AC4K43', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
