# Generated by Django 2.2.6 on 2019-10-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0054_auto_20191007_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='2K46L6', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='3333LP23', max_length=8, unique=True, verbose_name='Invoice ID'),
        ),
    ]
