# Generated by Django 2.2.6 on 2019-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0055_auto_20191007_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='2L4KA4', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, default='LF62D42D', max_length=8, unique=True, verbose_name='Invoice ID'),
        ),
    ]
