# Generated by Django 2.2.6 on 2019-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0060_auto_20191022_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='W536KK', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
