# Generated by Django 2.2.6 on 2019-10-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0061_auto_20191022_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='connection_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='45L5A6', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
