# Generated by Django 2.2.6 on 2019-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0062_auto_20191022_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='A52CA2', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billing_start_date',
            field=models.DateField(blank=True),
        ),
    ]
