# Generated by Django 2.2.6 on 2019-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0063_auto_20191022_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='43C6PL', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
