# Generated by Django 2.2.6 on 2019-10-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0070_auto_20191025_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='2LP45C', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
