# Generated by Django 2.2.6 on 2019-10-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0072_auto_20191025_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='223P6P', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billing_start_date',
            field=models.DateField(),
        ),
    ]
