# Generated by Django 2.2.6 on 2019-10-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0074_auto_20191025_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billhistory',
            options={'ordering': ['-date_version']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='L24CY5', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
