# Generated by Django 2.2.6 on 2019-10-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0076_auto_20191025_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='Y354L3', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
