# Generated by Django 2.2.6 on 2019-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0077_auto_20191025_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='celery_update',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='656AWL', max_length=6, unique=True, verbose_name='Bill ID'),
        ),
    ]
