# Generated by Django 2.2.6 on 2019-10-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191021_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_self_profile', 'Can view self profile only'), ('can_view_any_profile', 'Can view any profile')]},
        ),
    ]
