# Generated by Django 2.2.6 on 2019-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191023_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Manager'), ('3', 'Editor'), ('4', 'Worker'), ('5', 'Guest')], default='5', max_length=1),
        ),
    ]
