# Generated by Django 2.2.6 on 2019-10-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191025_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Manager'), ('3', 'Worker'), ('4', 'Guest')], default='4', max_length=1),
        ),
    ]
